### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [61]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [62]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[62, 27, 57, 76],
       [48, 31, 74, 72],
       [36, 54, 76, 90],
       [33, 55, 78, 37],
       [44, 98, 30, 68],
       [48, 62, 78, 17]])

In [63]:
np.sort(a)[::-1]

array([90, 84, 83, 83, 63, 62, 54, 52, 48, 47, 45, 36, 15, 11,  5])

In [64]:
np.sort(b,axis=0)

array([[33, 27, 30, 17],
       [36, 31, 57, 37],
       [44, 54, 74, 68],
       [48, 55, 76, 72],
       [48, 62, 78, 76],
       [62, 98, 78, 90]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [65]:
# code
np.append(a,200)

array([ 36,  15,  11,  83,  45,  63,  47,  90,  62,  84,  48,  52,  83,
        54,   5, 200])

In [66]:
b

array([[62, 27, 57, 76],
       [48, 31, 74, 72],
       [36, 54, 76, 90],
       [33, 55, 78, 37],
       [44, 98, 30, 68],
       [48, 62, 78, 17]])

In [67]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[6.20000000e+01, 2.70000000e+01, 5.70000000e+01, 7.60000000e+01,
        6.43953509e-01],
       [4.80000000e+01, 3.10000000e+01, 7.40000000e+01, 7.20000000e+01,
        8.32901166e-01],
       [3.60000000e+01, 5.40000000e+01, 7.60000000e+01, 9.00000000e+01,
        1.00509851e-02],
       [3.30000000e+01, 5.50000000e+01, 7.80000000e+01, 3.70000000e+01,
        3.45565538e-01],
       [4.40000000e+01, 9.80000000e+01, 3.00000000e+01, 6.80000000e+01,
        4.52412978e-01],
       [4.80000000e+01, 6.20000000e+01, 7.80000000e+01, 1.70000000e+01,
        1.74424965e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [68]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [69]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [71]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [72]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [73]:
# code
a.shape

(15,)

In [74]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [75]:
np.expand_dims(a,axis=1)

array([[36],
       [15],
       [11],
       [83],
       [45],
       [63],
       [47],
       [90],
       [62],
       [84],
       [48],
       [52],
       [83],
       [54],
       [ 5]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [76]:
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [77]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  5,  7,  8,  9, 11, 12, 13], dtype=int64),)

In [78]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([36, 15, 11,  0, 45,  0, 47,  0,  0,  0, 48,  0,  0,  0,  5])

In [79]:
np.where(a%2 == 0,0,a)

array([ 0, 15, 11, 83, 45, 63, 47,  0,  0,  0,  0,  0, 83,  0,  5])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [80]:
# code
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [81]:
np.argmax(a)

7

In [82]:
b

array([[62, 27, 57, 76],
       [48, 31, 74, 72],
       [36, 54, 76, 90],
       [33, 55, 78, 37],
       [44, 98, 30, 68],
       [48, 62, 78, 17]])

In [83]:
np.argmax(b,axis=0)

array([0, 4, 3, 2], dtype=int64)

In [84]:
np.argmax(b,axis=1)

array([3, 2, 3, 2, 1, 2], dtype=int64)

In [85]:
# np.argmin
np.argmin(a)

14

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [86]:
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [87]:
np.cumsum(a)

array([ 36,  51,  62, 145, 190, 253, 300, 390, 452, 536, 584, 636, 719,
       773, 778])

In [88]:
b

array([[62, 27, 57, 76],
       [48, 31, 74, 72],
       [36, 54, 76, 90],
       [33, 55, 78, 37],
       [44, 98, 30, 68],
       [48, 62, 78, 17]])

In [89]:
np.cumsum(b,axis=1)

array([[ 62,  89, 146, 222],
       [ 48,  79, 153, 225],
       [ 36,  90, 166, 256],
       [ 33,  88, 166, 203],
       [ 44, 142, 172, 240],
       [ 48, 110, 188, 205]])

In [90]:
np.cumsum(b)

array([  62,   89,  146,  222,  270,  301,  375,  447,  483,  537,  613,
        703,  736,  791,  869,  906,  950, 1048, 1078, 1146, 1194, 1256,
       1334, 1351])

In [91]:
# np.cumprod
np.cumprod(a)

array([         36,         540,        5940,      493020,    22185900,
        1397711700,  1267940460, -1849475592,  1296630288,  1542761792,
        1038121984, -1852231680,   883593216,   469393408, -1948000256])

In [92]:
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [93]:
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [94]:
np.percentile(a,50)

52.0

In [95]:
np.median(a)

52.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [96]:
# code
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [97]:
np.histogram(a,bins=[0,50,100])

(array([7, 8], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [98]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [99]:
# code
a


array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [100]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [101]:
# code
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [102]:
np.flip(a)

array([ 5, 54, 83, 52, 48, 84, 62, 90, 47, 63, 45, 83, 11, 15, 36])

In [103]:
b

array([[62, 27, 57, 76],
       [48, 31, 74, 72],
       [36, 54, 76, 90],
       [33, 55, 78, 37],
       [44, 98, 30, 68],
       [48, 62, 78, 17]])

In [104]:
np.flip(b,axis=1)

array([[76, 57, 27, 62],
       [72, 74, 31, 48],
       [90, 76, 54, 36],
       [37, 78, 55, 33],
       [68, 30, 98, 44],
       [17, 78, 62, 48]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [105]:
# code
a

array([36, 15, 11, 83, 45, 63, 47, 90, 62, 84, 48, 52, 83, 54,  5])

In [106]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [107]:
# code
a

array([110, 530,  11,  83,  45,  63,  47,  90,  62,  84,  48,  52,  83,
        54,   5])

In [108]:
np.delete(a,[0,2,4])

array([530,  83,  63,  47,  90,  62,  84,  48,  52,  83,  54,   5])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [109]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [110]:
np.intersect1d(m,n)

array([3, 4, 5])

In [111]:
np.setdiff1d(n,m)

array([6, 7])

In [112]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [113]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [114]:
# code
a

array([110, 530,  11,  83,  45,  63,  47,  90,  62,  84,  48,  52,  83,
        54,   5])

In [115]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 45, 63, 47, 75, 62, 75, 48, 52, 75, 54, 25])

In [116]:
# 17. np.swapaxes

In [117]:
# 18. np.uniform

In [118]:
# 19. np.count_nonzero

In [119]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [120]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [121]:

# 25. np.allclose and equals

# End